import Foundation

/// Strings are written in Russian in the code and serve as keys; English comes from en.lproj/Localizable.strings
/// (generated by scripts/l10n/make_strings.py). The interface follows the first language of macOS that the app has
/// (Russian or English), and a language chosen for Slovo wins: in Settings, or in System Settings → Language & Region →
/// Applications, which is the same choice (the app's own `AppleLanguages`, see `InterfaceLanguage`). That is the
/// localization macOS itself picks for the app, so menus and system panels match. It is picked once per launch, so a new
/// choice takes effect after a restart.
public enum Localization {
    /// "ru" or "en" for this launch.
    public static let current: String = {
        // A development build without the bundle has no translations: the keys are Russian.
        guard Bundle.main.path(forResource: "en", ofType: "lproj") != nil else { return "ru" }
        return Bundle.main.preferredLocalizations.first?.hasPrefix("ru") == true ? "ru" : "en"
    }()

    /// Call as early as possible at launch.
    public static func apply() {
        _ = current
    }

    /// Number style of the interface language ("1,08 ГБ" in Russian, "1.08 GB" in English).
    public static let numberLocale = Locale(identifier: current == "ru" ? "ru_RU" : "en_US")

    static func string(_ key: String) -> String {
        bundle?.localizedString(forKey: key, value: key, table: nil) ?? key
    }

    private static let bundle: Bundle? = {
        guard current != "ru", let path = Bundle.main.path(forResource: current, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }()
}

/// Localized string. `key` is the Russian text; `%@` placeholders are filled with `args`.
public func L(_ key: String, _ args: CVarArg...) -> String {
    let text = Localization.string(key)
    return args.isEmpty ? text : String(format: text, arguments: args)
}

/// File size written in the number style of the interface language.
public func formatBytes(_ count: Int64) -> String {
    count.formatted(.byteCount(style: .file).locale(Localization.numberLocale))
}

/// Duration as "12:34" or "1:02:03".
public func formatDuration(_ seconds: Double) -> String {
    let total = Int(max(0, seconds).rounded())
    let h = total / 3600, m = (total / 60) % 60, s = total % 60
    return h > 0 ? String(format: "%d:%02d:%02d", h, m, s) : String(format: "%d:%02d", m, s)
}

/// A number in the interface language with the right plural form of the noun:
/// pluralize(n, "слово", "слова", "слов", en: "word", "words").
public func pluralize(_ n: Int, _ one: String, _ few: String, _ many: String, en enOne: String, _ enMany: String) -> String {
    let number = n.formatted(.number.locale(Localization.numberLocale))
    if Localization.current != "ru" {
        return "\(number) \(n == 1 ? enOne : enMany)"
    }
    let mod10 = n % 10, mod100 = n % 100
    let word: String
    if mod10 == 1 && mod100 != 11 {
        word = one
    } else if (2...4).contains(mod10) && !(12...14).contains(mod100) {
        word = few
    } else {
        word = many
    }
    return "\(number) \(word)"
}
