import Foundation

/// Strings are written in Russian in the code and serve as keys; English comes from en.lproj/Localizable.strings
/// (generated by scripts/l10n/make_strings.py). As in Subtits, the interface is Russian when Russian is one of
/// the Mac's languages, otherwise English; a language chosen for the app in System Settings → Language & Region
/// → Applications wins. Menus and system panels follow through the app's own `AppleLanguages` setting.
public enum Localization {
    /// A language chosen for the app in System Settings ("ru" / "en"); absent for the automatic choice.
    private static let choiceKey = "MPXTransLanguage"
    /// The language last written to `AppleLanguages`, to tell it apart from a choice made in System Settings.
    private static let appliedKey = "MPXTransAppliedLanguage"

    /// "ru" or "en" for this launch.
    public static let current: String = {
        // A development build without the bundle has no translations: the keys are Russian.
        guard Bundle.main.path(forResource: "en", ofType: "lproj") != nil else { return "ru" }
        let defaults = UserDefaults.standard
        let domain = Bundle.main.bundleIdentifier.flatMap(defaults.persistentDomain(forName:)) ?? [:]
        let written = (domain["AppleLanguages"] as? [String])?.first
        let applied = domain[appliedKey] as? String
        if let written, applied.map({ !written.hasPrefix($0) }) ?? true {
            defaults.set(written.hasPrefix("ru") ? "ru" : "en", forKey: choiceKey)
        } else if written == nil, applied != nil {
            // "System Language" was chosen for the app again.
            defaults.removeObject(forKey: choiceKey)
        }
        let systemLanguages = defaults.persistentDomain(forName: UserDefaults.globalDomain)?["AppleLanguages"] as? [String]
            ?? Locale.preferredLanguages
        let code = defaults.string(forKey: choiceKey) ?? (systemLanguages.contains { $0.hasPrefix("ru") } ? "ru" : "en")
        defaults.set([code], forKey: "AppleLanguages")
        defaults.set(code, forKey: appliedKey)
        return code
    }()

    /// Call as early as possible at launch so that menus and panels use the same language as the app.
    public static func apply() {
        _ = current
    }

    /// Number style of the interface language ("1,08 ГБ" in Russian, "1.08 GB" in English).
    public static let numberLocale = Locale(identifier: current == "ru" ? "ru_RU" : "en_US")

    static func string(_ key: String) -> String {
        bundle?.localizedString(forKey: key, value: key, table: nil) ?? key
    }

    private static let bundle: Bundle? = {
        guard current != "ru", let path = Bundle.main.path(forResource: current, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }()
}

/// Localized string. `key` is the Russian text; `%@` placeholders are filled with `args`.
public func L(_ key: String, _ args: CVarArg...) -> String {
    let text = Localization.string(key)
    return args.isEmpty ? text : String(format: text, arguments: args)
}

/// File size written in the number style of the interface language.
public func formatBytes(_ count: Int64) -> String {
    count.formatted(.byteCount(style: .file).locale(Localization.numberLocale))
}

/// Duration as "12:34" or "1:02:03".
public func formatDuration(_ seconds: Double) -> String {
    let total = Int(max(0, seconds).rounded())
    let h = total / 3600, m = (total / 60) % 60, s = total % 60
    return h > 0 ? String(format: "%d:%02d:%02d", h, m, s) : String(format: "%d:%02d", m, s)
}

/// A number in the interface language with the right plural form of the noun:
/// pluralize(n, "слово", "слова", "слов", en: "word", "words").
public func pluralize(_ n: Int, _ one: String, _ few: String, _ many: String, en enOne: String, _ enMany: String) -> String {
    let number = n.formatted(.number.locale(Localization.numberLocale))
    if Localization.current != "ru" {
        return "\(number) \(n == 1 ? enOne : enMany)"
    }
    let mod10 = n % 10, mod100 = n % 100
    let word: String
    if mod10 == 1 && mod100 != 11 {
        word = one
    } else if (2...4).contains(mod10) && !(12...14).contains(mod100) {
        word = few
    } else {
        word = many
    }
    return "\(number) \(word)"
}
